Add locks to BundleWiringImpl.
The lack of locking in findClassOrResourceByDelegation and loadClass is causing race conditions that manifest as NoClassDefFoundError in a killbill deployment.

This change works towards fixing these by adding synchronization.